name: boring
description: High-performance cryptography and PKI powered by BoringSSL with Dart Native Assets.
version: 0.3.0
repository: https://github.com/mosuem/boring

environment:
  sdk: ^3.10.0

dependencies:
  code_assets: ^2.1.0
  ffi: ^2.2.0
  hooks: ^2.2.0
  meta: ^1.19.0
  native_toolchain_cmake: ^0.3.2

dev_dependencies:
  args: ^2.7.0
  dart_flutter_team_lints: ^3.5.2
  ffigen: ^22.0.0
  test: ^1.32.0

hooks:
  user_defines:
    boring:
      buildMode: checkout

topics:
  - crypto
  - security
