// Copyright 2026 Moritz Sümmermann. Licensed under the Apache License,
// Version 2.0. See the LICENSE file for details.

import 'dart:io';
import 'package:ffigen/ffigen.dart';

Future<void> main() async {
  final packageRoot = Platform.script.resolve('../');

  print('Generating Dart FFI bindings for BoringSSL (bssl_dart)...');

  await FfiGenerator(
    output: Output(
      dart: DartOutput(
        path: packageRoot.resolve('lib/src/bindings/boringssl.g.dart'),
      ),
      style: const NativeExternalBindings(
        assetId: 'package:boring/boring.dart',
      ),
      format: true,
      commentType: const CommentType(CommentStyle.any, CommentLength.full),
      preamble: '''
// Copyright 2026 Moritz Sümmermann. Licensed under the Apache License,
// Version 2.0. See the LICENSE file for details.

// AUTO-GENERATED BY tool/ffigen.dart - DO NOT MODIFY.
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_element
// ignore_for_file: unused_field
''',
    ),
    input: Input(
      entryPoints: [
        packageRoot.resolve('src/wrapper.h'),
      ],
      compilerOptions: const [
        '-Ithird_party/boringssl/src/include',
        '-DBORINGSSL_PREFIX=bssl_dart',
        '-U__PRAGMA_REDEFINE_EXTNAME',
      ],
    ),
    visitors: [
      Visitor(
        func: (node) {
          final name = node.originalName;
          node.isIncluded = name.startsWith('bssl_dart_');
          if (name.startsWith('bssl_dart_')) {
            node.name = name.substring('bssl_dart_'.length);
          }
        },
        struct: (node) {
          node.isIncluded = true;
          node.dependencies = CompoundDependencies.opaque;
        },
        typealias: (node) {
          node.isIncluded = TypealiasInclude.always;
        },
        macroConstant: (node) {
          final name = node.originalName;
          node.isIncluded =
              name.startsWith('bssl_dart_') ||
              name.startsWith('EVP_') ||
              name.startsWith('NID_') ||
              name.startsWith('RSA_') ||
              name.startsWith('X509_') ||
              name.startsWith('V_ASN1_') ||
              name.startsWith('CBS_ASN1_') ||
              name.startsWith('MBSTRING_') ||
              name.startsWith('AES_');
          if (name.startsWith('bssl_dart_')) {
            node.name = name.substring('bssl_dart_'.length);
          }
        },
      ),
    ],
  ).generate();

  print('BoringSSL FFI bindings generated successfully.');
}
