// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:io';
import 'package:ffigen/ffigen.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');

  print('Generating Dart FFI bindings for BoringSSL (bssl_dart)...');

  FfiGenerator(
    output: Output(
      dartFile: packageRoot.resolve(
        'lib/src/bindings/boringssl.g.dart',
      ),
      style: const NativeExternalBindings(
        assetId: 'package:boring/boring.dart',
      ),
      format: true,
      commentType: const CommentType(CommentStyle.any, CommentLength.full),
      preamble: '''
// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// AUTO-GENERATED BY tool/ffigen.dart - DO NOT MODIFY.
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_element
// ignore_for_file: unused_field
''',
    ),
    headers: Headers(
      entryPoints: [
        packageRoot.resolve('src/wrapper.h'),
      ],
      compilerOptions: [
        '-Ithird_party/boringssl/src/include',
        '-DBORINGSSL_PREFIX=bssl_dart',
        '-U__PRAGMA_REDEFINE_EXTNAME',
      ],
    ),
    functions: Functions(
      include: (decl) => decl.originalName.startsWith('bssl_dart_'),
      rename: (decl) {
        final name = decl.originalName;
        if (name.startsWith('bssl_dart_')) {
          return name.substring('bssl_dart_'.length);
        }
        return name;
      },
    ),
    structs: const Structs(
      include: Declarations.includeAll,
      dependencies: CompoundDependencies.opaque,
    ),
    typedefs: Typedefs.includeAll,
    macros: Macros(
      include: (decl) =>
          decl.originalName.startsWith('bssl_dart_') ||
          decl.originalName.startsWith('EVP_') ||
          decl.originalName.startsWith('NID_') ||
          decl.originalName.startsWith('RSA_') ||
          decl.originalName.startsWith('X509_') ||
          decl.originalName.startsWith('V_ASN1_') ||
          decl.originalName.startsWith('MBSTRING_') ||
          decl.originalName.startsWith('AES_'),
      rename: (decl) {
        final name = decl.originalName;
        if (name.startsWith('bssl_dart_')) {
          return name.substring('bssl_dart_'.length);
        }
        return name;
      },
    ),
  ).generate();

  print('BoringSSL FFI bindings generated successfully.');
}
