// Copyright 2026 Moritz Sümmermann. Licensed under the Apache License,
// Version 2.0. See the LICENSE file for details.

// coverage:ignore-file

import 'dart:io';
import 'dart:typed_data';

import 'package:boring/src/hook_helpers/sha256.dart';
import 'package:boring/src/hook_helpers/targets.dart';
import 'package:boring/src/hook_helpers/version.dart';
import 'package:code_assets/code_assets.dart';

Future<void> main(List<String> args) async {
  final version = args.isNotEmpty ? args[0] : releaseVersion;
  final httpClient = HttpClient();

  stdout.writeln('Checking hashes for version $version...');
  final fileHashes = <String, String>{};

  for (final (os, arch, iosSdk) in supportedTargets) {
    final targetTriple = targetTripleFor(os, arch, iosSdk: iosSdk);
    final dylibFileName = os.dylibFileName('bssl_dart');
    final assetRemoteName = 'boring-$targetTriple-$dylibFileName';
    final uri = Uri.parse(
      'https://github.com/mosuem/boring/releases/download/v$version/$assetRemoteName',
    );

    stdout.writeln('Fetching from $uri...');
    try {
      final request = await httpClient.getUrl(uri);
      final response = await request.close();
      if (response.statusCode != 200) {
        stdout.writeln('  Skipping: status ${response.statusCode}');
        continue;
      }
      final builder = BytesBuilder(copy: false);
      await response.forEach(builder.add);
      final bytes = builder.takeBytes();
      final fileHash = sha256Hex(bytes);
      fileHashes[targetTriple] = fileHash;
      stdout.writeln('  Target $targetTriple: $fileHash');
    } catch (e) {
      stdout.writeln('  Error fetching $uri: $e');
    }
  }
  httpClient.close(force: true);

  final buffer = StringBuffer()
    ..writeln(
      '// Copyright 2026 Moritz Sümmermann. Licensed under the Apache License,',
    )
    ..writeln('// Version 2.0. See the LICENSE file for details.')
    ..writeln()
    ..writeln('// coverage:ignore-file')
    ..writeln('// THIS FILE IS GENERATED BY `tool/regenerate_hashes.dart`.')
    ..writeln()
    ..writeln("const version = '$version';")
    ..writeln()
    ..writeln('/// Mapping from target triple string to SHA-256 hash.')
    ..writeln('const fileHashes = <String, String>{');

  for (final entry in fileHashes.entries) {
    buffer.writeln("  '${entry.key}':");
    buffer.writeln("      '${entry.value}',");
  }
  buffer.writeln('};');

  await File(
    'lib/src/hook_helpers/hashes.dart',
  ).writeAsString(buffer.toString());
  stdout.writeln(
    'Updated lib/src/hook_helpers/hashes.dart with ${fileHashes.length} hashes.',
  );
}
