// Copyright (c) 2026, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// coverage:ignore-file
// THIS FILE IS GENERATED BY `tool/regenerate_hashes.dart`.

import 'version.dart';

const version = releaseVersion;

/// Mapping from target triple string (e.g. 'linux-x64') to SHA-256 hash.
const fileHashes = <String, String>{};
