// Copyright 2026 Moritz Sümmermann. Licensed under the Apache License,
// Version 2.0. See the LICENSE file for details.

// coverage:ignore-file
// THIS FILE IS GENERATED BY `tool/regenerate_hashes.dart`.

import 'version.dart';

const version = releaseVersion;

/// Mapping from release asset name (see `releaseAssetName`) to
/// SHA-256 hash.
const fileHashes = <String, String>{};
